import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Dash.module.css";
import React, { useState } from "react";
import Navbar from "../components/Navbar";
import Calendar from "../components/Calendar"

export default function Dashboard() {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.main}>
                <div className={styles.header}>Dashboard</div>
                <div className={styles.boxes}>
                    <Calendar />
                </div>
            </div>
        </>
    );
}
